#!/usr/bin/env node
import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import { spawnSync } from "child_process";
import chalk from "chalk";
import { runAllChecks, type CheckStatus } from "../src/platform/detect";
import {
  getPlatformRoot,
  ensurePlatformDirectories,
  ensureRuntimeConfig,
  getRuntimeConfigPath,
  RUNTIME_DIRS,
  hasProjectConfig,
  loadProjectConfig,
  loadScope,
  saveScope,
  saveProjectConfig,
  saveProjectProfile,
  loadDockerEnv,
} from "../src/config/loader";
import { detectProjectStack } from "../src/discovery";
import { listProjects, registerProject } from "../src/config/registry";
import type { Profile } from "../src/config/schema";
import { installAgent, describeAgent, SUPPORTED_AGENTS, type AgentId } from "../install/index";
import { runAssessment } from "../src/orchestrator";
import { nucleiAdapter } from "../src/tools/nuclei";
import { zapAdapter } from "../src/tools/zap";
import { mobsfAdapter } from "../src/tools/mobsf";
import { strixAdapter } from "../src/tools/strix";
import type { Finding } from "../src/findings/schema";

const pkg = require(path.join(__dirname, "..", "..", "package.json"));

function notImplemented(command: string): void {
  console.log(chalk.yellow(`'security ${command}' is not implemented yet.`));
}

function statusTag(status: CheckStatus): string {
  switch (status) {
    case "ok":
      return chalk.green("[OK]     ");
    case "warning":
      return chalk.yellow("[WARNING]");
    case "error":
      return chalk.red("[ERROR]  ");
    default:
      return chalk.gray("[SKIPPED]");
  }
}

function logLine(platformRoot: string, message: string): void {
  const logsDir = path.join(platformRoot, "logs");
  fs.mkdirSync(logsDir, { recursive: true });
  const line = `${new Date().toISOString()} ${message}\n`;
  fs.appendFileSync(path.join(logsDir, "assessments.log"), line, "utf8");
}

function latestReportDir(platformRoot: string): string | null {
  const reportsDir = path.join(platformRoot, "reports");
  if (!fs.existsSync(reportsDir)) return null;
  // Sort by mtime, not name: report dirs are named
  // "assessment-YYYY-MM-DD-<random-id>", and the random id suffix means two
  // reports from the same day do NOT sort chronologically by name (e.g.
  // "...-0728e94f" can sort before "...-a7ef94a6" even though it was
  // generated later).
  const dirs = fs
    .readdirSync(reportsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => ({ name: d.name, mtimeMs: fs.statSync(path.join(reportsDir, d.name)).mtimeMs }))
    .sort((a, b) => a.mtimeMs - b.mtimeMs);
  return dirs.length > 0 ? path.join(reportsDir, dirs[dirs.length - 1].name) : null;
}

// Every command below may end up talking to a tool adapter (zap.ts/mobsf.ts)
// that reads its API key from process.env -- load docker/.env once, up
// front, so ZAP_API_KEY/MOBSF_API_KEY (generated by `security setup` /
// retrieved from MobSF's own logs) are visible without the user having to
// manually source the file.
loadDockerEnv(getPlatformRoot());

const program = new Command();

program
  .name("security")
  .description("Centralized AI-agent-driven security assessment platform")
  .version(pkg.version);

program
  .command("install")
  .argument("<agent>", `AI agent to configure (${SUPPORTED_AGENTS.join(", ")})`)
  .description("Configure MCP + deploy Security Skills for an AI agent in the current project")
  .action((agent: string) => {
    if (!(SUPPORTED_AGENTS as readonly string[]).includes(agent)) {
      console.log(chalk.red(`Unknown agent '${agent}'.`));
      console.log(`Supported agents: ${SUPPORTED_AGENTS.join(", ")}`);
      process.exitCode = 1;
      return;
    }
    const platformRoot = getPlatformRoot();
    const info = describeAgent(agent as AgentId);
    console.log(chalk.bold(`Installing ${info.label} integration in: ${process.cwd()}`));
    if (info.mcpConfig && !info.mcpVerified) {
      console.log(chalk.yellow(`[WARNING] MCP config path for '${agent}' is an unverified generic fallback (${info.mcpConfig}). Confirm against ${info.label}'s current docs if it doesn't take effect.`));
    }
    installAgent(agent, platformRoot, process.cwd());
    console.log(chalk.bold("\nAgent integration complete."));
  });

program
  .command("doctor")
  .description("Validate prerequisites (Node, Docker, WSL2, tool health)")
  .action(() => {
    console.log(chalk.bold("Security Platform Doctor\n"));

    let hasError = false;
    let hasWarning = false;
    for (const result of runAllChecks()) {
      console.log(`${statusTag(result.status)} ${result.name}: ${result.message}`);
      if (result.remediation) {
        console.log(chalk.gray(`           ${result.remediation}`));
      }
      if (result.status === "error") hasError = true;
      if (result.status === "warning") hasWarning = true;
    }

    const platformRoot = getPlatformRoot();
    console.log(chalk.bold(`\nPlatform root: ${platformRoot}`));
    const missingDirs = RUNTIME_DIRS.filter((d) => !fs.existsSync(path.join(platformRoot, d)));
    if (missingDirs.length > 0) {
      console.log(`${statusTag("warning")} Missing directories: ${missingDirs.join(", ")} -- run 'security setup' to create them.`);
      hasWarning = true;
    } else {
      console.log(`${statusTag("ok")} All platform directories present.`);
    }
    const configPath = getRuntimeConfigPath(platformRoot);
    if (fs.existsSync(configPath)) {
      console.log(`${statusTag("ok")} Runtime config present (${configPath}).`);
    } else {
      console.log(`${statusTag("warning")} Runtime config missing -- run 'security setup'.`);
      hasWarning = true;
    }

    console.log("");
    if (hasError) {
      console.log(chalk.red("Doctor found errors that must be fixed."));
      process.exitCode = 1;
    } else if (hasWarning) {
      console.log(chalk.yellow("Doctor found warnings. The CLI works, but some functionality is limited until they're resolved."));
    } else {
      console.log(chalk.green("Everything looks good."));
    }
  });

program
  .command("status")
  .description("Show platform and registered-project status")
  .action(() => {
    const platformRoot = getPlatformRoot();
    console.log(chalk.bold("Security Platform"));
    console.log(`  Root:        ${platformRoot}`);
    const configured = fs.existsSync(getRuntimeConfigPath(platformRoot));
    console.log(`  Configured:  ${configured ? chalk.green("yes") : chalk.yellow("no (run 'security setup')")}`);

    const projects = listProjects(platformRoot);
    console.log(chalk.bold(`\nRegistered projects (${projects.length}):`));
    if (projects.length === 0) {
      console.log("  (none yet -- run 'security setup' inside a project)");
    } else {
      for (const p of projects) {
        console.log(`  - ${chalk.bold(p.name)}  ${chalk.gray(p.path)}`);
        console.log(`      profiles: ${p.profiles.join(", ") || "(none detected)"}`);
        console.log(`      registered: ${p.registeredAt}  last assessment: ${p.lastAssessment ?? "(never)"}`);
      }
    }
  });

program
  .command("update")
  .description("Update the platform (git pull + rebuild) where this is a git checkout")
  .action(() => {
    const platformRoot = getPlatformRoot();
    const isGitRepo = fs.existsSync(path.join(platformRoot, ".git"));
    if (!isGitRepo) {
      console.log(chalk.yellow(`${platformRoot} is not a git checkout -- nothing to pull. If you installed via npm, use: npm install -g security-platform@latest`));
      return;
    }
    console.log(chalk.bold("Pulling latest changes..."));
    const pull = spawnSync("git", ["-C", platformRoot, "pull", "--ff-only"], { stdio: "inherit", shell: process.platform === "win32" });
    if (pull.status !== 0) {
      console.log(chalk.red("git pull failed. Resolve manually (check for local changes) and re-run."));
      process.exitCode = 1;
      return;
    }
    console.log(chalk.bold("\nRebuilding..."));
    const install = spawnSync("npm", ["install"], { cwd: platformRoot, stdio: "inherit", shell: process.platform === "win32" });
    const build = install.status === 0 ? spawnSync("npm", ["run", "build"], { cwd: platformRoot, stdio: "inherit", shell: process.platform === "win32" }) : install;
    if (build.status !== 0) {
      console.log(chalk.red("Update failed during install/build. See output above."));
      process.exitCode = 1;
      return;
    }
    console.log(chalk.green("\nUpdate complete."));
  });

program
  .command("repair")
  .description("Repair recoverable platform state (missing directories/config)")
  .action(() => {
    const platformRoot = getPlatformRoot();
    console.log(chalk.bold(`Repairing platform at: ${platformRoot}`));
    let repaired = 0;
    for (const dir of ensurePlatformDirectories(platformRoot)) {
      if (dir.created) {
        console.log(chalk.green(`[SUCCESS] Recreated missing directory: ${dir.dirPath}`));
        repaired++;
      }
    }
    const runtimeConfig = ensureRuntimeConfig(platformRoot);
    if (runtimeConfig.created) {
      console.log(chalk.green(`[SUCCESS] Recreated missing runtime config: ${runtimeConfig.path}`));
      repaired++;
    }
    const composePath = path.join(platformRoot, "docker", "docker-compose.yml");
    if (!fs.existsSync(composePath)) {
      console.log(chalk.red(`[ERROR] docker/docker-compose.yml is missing -- this cannot be auto-repaired; re-clone or restore it.`));
      process.exitCode = 1;
    } else {
      const check = spawnSync("docker", ["compose", "-f", composePath, "config"], { encoding: "utf8", shell: process.platform === "win32" });
      if (check.status === 0) {
        console.log(chalk.green("[OK]      docker-compose.yml is valid."));
      } else {
        console.log(chalk.yellow(`[WARNING] docker-compose.yml did not validate (is docker/.env missing ZAP_API_KEY?): ${check.stderr?.trim()}`));
      }
    }
    console.log(repaired > 0 ? chalk.bold(`\nRepair complete: ${repaired} item(s) fixed.`) : chalk.bold("\nNothing to repair -- platform state was already intact."));
  });

program
  .command("setup")
  .description("Global platform setup, or (run inside a project) project setup")
  .action(() => {
    const platformRoot = getPlatformRoot();
    console.log(chalk.bold(`Security Platform root: ${platformRoot}`));

    for (const dir of ensurePlatformDirectories(platformRoot)) {
      console.log(dir.created ? chalk.green(`[SUCCESS] Created ${dir.dirPath}`) : chalk.gray(`[INFO] ${dir.dirPath} already exists`));
    }
    const runtimeConfig = ensureRuntimeConfig(platformRoot);
    console.log(
      runtimeConfig.created
        ? chalk.green(`[SUCCESS] Wrote ${runtimeConfig.path}`)
        : chalk.gray(`[INFO] ${runtimeConfig.path} already exists`)
    );

    const dockerEnvPath = path.join(platformRoot, "docker", ".env");
    if (!fs.existsSync(dockerEnvPath)) {
      const zapKey = require("crypto").randomBytes(16).toString("hex");
      fs.writeFileSync(
        dockerEnvPath,
        `ZAP_API_KEY=${zapKey}\nZAP_API_PORT=8090\nZAP_VERSION=latest\nMOBSF_PORT=8000\nMOBSF_VERSION=latest\nNUCLEI_VERSION=latest\n`,
        "utf8"
      );
      console.log(chalk.green(`[SUCCESS] Generated ${dockerEnvPath} with a random ZAP_API_KEY.`));
    } else {
      console.log(chalk.gray(`[INFO] ${dockerEnvPath} already exists.`));
    }

    const cwd = process.cwd();
    const isPlatformRoot = path.resolve(cwd).toLowerCase() === path.resolve(platformRoot).toLowerCase();
    if (isPlatformRoot) {
      console.log(chalk.cyan("\nRunning from the platform root -- global setup only; no project to configure here."));
      console.log(chalk.bold("\nGlobal setup complete."));
      console.log(`Run ${chalk.cyan("security doctor")} to verify the full prerequisite/service picture.`);
      return;
    }

    console.log(chalk.bold(`\nDetecting project stack in: ${cwd}`));
    const detected = detectProjectStack(cwd);
    const detectedNames = (Object.keys(detected) as Array<keyof typeof detected>).filter((k) => detected[k]);
    if (detectedNames.length === 0) {
      console.log(chalk.yellow("[WARNING] No supported technologies detected in this directory."));
    } else {
      console.log(chalk.green(`[SUCCESS] Detected: ${detectedNames.join(", ")}`));
    }

    const profiles = new Set<Profile>();
    if (detected.laravel) profiles.add("web");
    if (detected.api || detected.laravel) profiles.add("api");
    if (detected.android) profiles.add("mobile");
    if (detected.windows) profiles.add("windows");
    if (detected.webview) profiles.add("webview");
    if (profiles.size === 0) profiles.add("quick");
    const activeProfiles = Array.from(profiles);

    const projectName = path.basename(cwd);
    const alreadyConfigured = hasProjectConfig(cwd);

    saveProjectConfig(cwd, {
      schemaVersion: 1,
      name: projectName,
      detected,
      profiles: activeProfiles,
      mcp: { registered: false },
    });

    if (loadScope(cwd)) {
      console.log(chalk.gray("[INFO] .security/scope.yaml already exists, leaving it unchanged."));
    } else {
      saveScope(cwd, {
        schemaVersion: 1,
        environment: "staging",
        allowedDomains: [],
        allowedIpRanges: [],
        allowedUrls: [],
        allowedRepositories: [],
        allowedApplications: [],
        allowedMobileArtifacts: [],
        excludedHosts: [],
        excludedPaths: [],
        authenticationProfiles: [],
        rateLimits: { requestsPerSecond: 5 },
        maxScanDurationMinutes: 60,
        destructiveActionsAllowed: false,
      });
      console.log(chalk.green("[SUCCESS] Created .security/scope.yaml -- edit it before scanning; the default scope authorizes nothing."));
    }

    saveProjectProfile(cwd, { schemaVersion: 1, activeProfiles });

    console.log(
      alreadyConfigured
        ? chalk.green(`[SUCCESS] Updated .security/config.yaml for '${projectName}'.`)
        : chalk.green(`[SUCCESS] Created .security/ for '${projectName}'.`)
    );

    const registered = registerProject(platformRoot, { name: projectName, path: cwd, profiles: activeProfiles });
    console.log(chalk.green(`[SUCCESS] Registered with the platform (first registered: ${registered.registeredAt}).`));

    console.log(chalk.bold("\nProject setup complete."));
    console.log(
      `Next: edit ${chalk.cyan(".security/scope.yaml")} to authorize a target, then run ${chalk.cyan(
        "security scan --full"
      )}, or ask your AI agent to run a security assessment.`
    );
  });

program
  .command("config")
  .description("View project security configuration")
  .action(() => {
    const config = loadProjectConfig(process.cwd());
    if (!config) {
      console.log(chalk.yellow("No .security/config.yaml found here. Run 'security setup' first."));
      process.exitCode = 1;
      return;
    }
    console.log(JSON.stringify(config, null, 2));
  });

program
  .command("scope")
  .description("View, or add an authorized target to, the project's assessment scope")
  .option("--add-url <url>", "Add a URL to allowedUrls")
  .option("--add-domain <domain>", "Add a domain to allowedDomains")
  .option("--add-artifact <path>", "Add a mobile artifact path to allowedMobileArtifacts")
  .action((opts: { addUrl?: string; addDomain?: string; addArtifact?: string }) => {
    const cwd = process.cwd();
    const scope = loadScope(cwd);
    if (!scope) {
      console.log(chalk.yellow("No .security/scope.yaml found here. Run 'security setup' first."));
      process.exitCode = 1;
      return;
    }
    let changed = false;
    if (opts.addUrl && !scope.allowedUrls.includes(opts.addUrl)) {
      scope.allowedUrls.push(opts.addUrl);
      changed = true;
    }
    if (opts.addDomain && !scope.allowedDomains.includes(opts.addDomain)) {
      scope.allowedDomains.push(opts.addDomain);
      changed = true;
    }
    if (opts.addArtifact && !scope.allowedMobileArtifacts.includes(opts.addArtifact)) {
      scope.allowedMobileArtifacts.push(opts.addArtifact);
      changed = true;
    }
    if (changed) {
      saveScope(cwd, scope);
      console.log(chalk.green("[SUCCESS] Scope updated."));
    }
    console.log(JSON.stringify(scope, null, 2));
  });

program
  .command("scan")
  .description("Run a security assessment against the current project's configured scope")
  .option("--full", "Run all applicable tools (default)")
  .option("--web", "Web-focused (informational; tool selection is still driven by detected stack + scope)")
  .option("--api", "API-focused (informational; see --web)")
  .option("--mobile", "Mobile-focused (informational; see --web)")
  .option("--windows", "Windows-focused (no automated Windows scanner yet -- see windows-security skill)")
  .option("--webview", "WebView-focused (covered via the android/windows adapters + webview-security skill)")
  .action(async (opts: Record<string, boolean>) => {
    const cwd = process.cwd();
    const platformRoot = getPlatformRoot();
    const flags = Object.keys(opts).filter((k) => opts[k]);
    if (flags.length > 0 && !flags.includes("full")) {
      console.log(chalk.gray(`[INFO] --${flags.join(", --")} noted, but per-profile filtering isn't implemented yet -- running every tool applicable to the detected stack and configured scope.`));
    }
    console.log(chalk.bold(`Running security assessment for: ${cwd}`));
    try {
      const result = await runAssessment({ platformRoot, projectPath: cwd });
      logLine(platformRoot, `assessment ${result.assessmentId} project=${cwd} findings=${result.findings.length} tools=${result.toolsRun.join(",")}`);

      console.log(chalk.bold(`\nTools run: ${result.toolsRun.join(", ") || "(none)"}`));
      if (result.toolsSkipped.length > 0) {
        console.log(chalk.yellow("Tools skipped:"));
        for (const s of result.toolsSkipped) console.log(chalk.yellow(`  - ${s.name}: ${s.reason}`));
      }
      if (result.errors.length > 0) {
        console.log(chalk.red("Errors:"));
        for (const e of result.errors) console.log(chalk.red(`  - ${e.tool} against ${e.target}: ${e.message}`));
      }
      console.log(chalk.bold(`\nFindings: ${result.findings.length}`));
      console.log(`Report: ${result.reportDir}`);
    } catch (err) {
      console.log(chalk.red(`[ERROR] ${(err as Error).message}`));
      process.exitCode = 1;
    }
  });

program
  .command("findings")
  .description("List findings from the most recent assessment report")
  .action(() => {
    const platformRoot = getPlatformRoot();
    const dir = latestReportDir(platformRoot);
    if (!dir) {
      console.log(chalk.yellow("No reports found. Run 'security scan' first."));
      return;
    }
    const findingsPath = path.join(dir, "findings.json");
    if (!fs.existsSync(findingsPath)) {
      console.log(chalk.yellow(`No findings.json in ${dir}.`));
      return;
    }
    const data = JSON.parse(fs.readFileSync(findingsPath, "utf8")) as { findings: Finding[] };
    if (data.findings.length === 0) {
      console.log("No findings in the most recent report.");
      return;
    }
    for (const f of data.findings) {
      console.log(`[${f.severity.toUpperCase()}] ${f.title}  (${f.confidence}, ${f.status})  ${f.endpoint ?? f.component}  id=${f.id}`);
    }
  });

program
  .command("report")
  .description("Show the location and summary of the most recent assessment report")
  .action(() => {
    const platformRoot = getPlatformRoot();
    const dir = latestReportDir(platformRoot);
    if (!dir) {
      console.log(chalk.yellow("No reports found. Run 'security scan' first."));
      return;
    }
    console.log(chalk.bold(`Latest report: ${dir}`));
    for (const file of ["executive-summary.md", "security-report.html", "findings.json"]) {
      const p = path.join(dir, file);
      console.log(`  ${fs.existsSync(p) ? chalk.green("[OK]") : chalk.red("[MISSING]")} ${p}`);
    }
  });

program
  .command("reset")
  .description("Reset local platform state (does not touch project source)")
  .option("--yes", "Confirm the reset")
  .action((opts: { yes?: boolean }) => {
    if (!opts.yes) {
      console.log(chalk.yellow("This removes projects/registry.json and config/runtime.yaml. Re-run with --yes to confirm."));
      return;
    }
    const platformRoot = getPlatformRoot();
    for (const rel of [path.join("projects", "registry.json"), path.join("config", "runtime.yaml")]) {
      const p = path.join(platformRoot, rel);
      if (fs.existsSync(p)) {
        fs.unlinkSync(p);
        console.log(chalk.green(`[SUCCESS] Removed ${p}`));
      }
    }
    console.log(chalk.bold("Platform state reset. Run 'security setup' to reinitialize."));
  });

program
  .command("clean")
  .description("Remove generated reports/evidence older than the retention period")
  .option("--days <n>", "Retention period in days", "30")
  .action((opts: { days: string }) => {
    const platformRoot = getPlatformRoot();
    const cutoff = Date.now() - parseInt(opts.days, 10) * 24 * 60 * 60 * 1000;
    let removed = 0;
    for (const sub of ["reports", "evidence"]) {
      const dir = path.join(platformRoot, sub);
      if (!fs.existsSync(dir)) continue;
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const entryPath = path.join(dir, entry.name);
        const stat = fs.statSync(entryPath);
        if (stat.mtimeMs < cutoff) {
          fs.rmSync(entryPath, { recursive: true, force: true });
          console.log(chalk.green(`[SUCCESS] Removed ${entryPath}`));
          removed++;
        }
      }
    }
    console.log(chalk.bold(`Clean complete: ${removed} item(s) removed (older than ${opts.days} days).`));
  });

program
  .command("logs")
  .description("Show recent assessment log lines")
  .option("--lines <n>", "Number of lines to show", "50")
  .action((opts: { lines: string }) => {
    const platformRoot = getPlatformRoot();
    const logPath = path.join(platformRoot, "logs", "assessments.log");
    if (!fs.existsSync(logPath)) {
      console.log("No logs yet -- run 'security scan' first.");
      return;
    }
    const lines = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
    const n = parseInt(opts.lines, 10);
    console.log(lines.slice(-n).join("\n"));
  });

program
  .command("tools")
  .description("List managed security tools and their health")
  .action(async () => {
    for (const adapter of [nucleiAdapter, zapAdapter, mobsfAdapter, strixAdapter]) {
      const health = await adapter.checkHealth();
      console.log(`${health.available ? statusTag("ok") : statusTag("warning")} ${adapter.name}: ${health.available ? health.version ?? "available" : health.detail}`);
    }
  });

program
  .command("projects")
  .description("List projects registered with the platform")
  .action(() => {
    const platformRoot = getPlatformRoot();
    const projects = listProjects(platformRoot);
    if (projects.length === 0) {
      console.log("(none yet -- run 'security setup' inside a project)");
      return;
    }
    for (const p of projects) {
      console.log(`${chalk.bold(p.name)}  ${chalk.gray(p.path)}  [${p.profiles.join(", ") || "no profiles"}]`);
    }
  });

program
  .command("validate")
  .argument("<findingId>", "Finding id from the most recent report")
  .description("Show a finding's detail, optionally updating its status/confidence after manual validation")
  .option("--status <status>", "New status: suspected|probable|confirmed|false_positive|unable_to_validate")
  .option("--note <note>", "Validation note, recorded as an evidence entry")
  .action((findingId: string, opts: { status?: string; note?: string }) => {
    const platformRoot = getPlatformRoot();
    const dir = latestReportDir(platformRoot);
    if (!dir) {
      console.log(chalk.yellow("No reports found."));
      return;
    }
    const findingsPath = path.join(dir, "findings.json");
    const data = JSON.parse(fs.readFileSync(findingsPath, "utf8")) as { meta: unknown; findings: Finding[] };
    const finding = data.findings.find((f) => f.id === findingId);
    if (!finding) {
      console.log(chalk.red(`No finding with id '${findingId}' in the latest report.`));
      process.exitCode = 1;
      return;
    }
    if (opts.status) {
      finding.status = opts.status as Finding["status"];
      finding.validated_by = Array.from(new Set([...finding.validated_by, "manual"]));
      if (opts.note) finding.evidence.push(`[validation note] ${opts.note}`);
      fs.writeFileSync(findingsPath, JSON.stringify(data, null, 2), "utf8");
      console.log(chalk.green(`[SUCCESS] Updated ${findingId} -> status=${finding.status}`));
    }
    console.log(JSON.stringify(finding, null, 2));
  });

program
  .command("mcp")
  .description("Start the Security MCP server on stdio (invoked by AI agents, not typically run by hand)")
  .action(async () => {
    const { startMcpServer } = await import("../src/mcp/server.js");
    await startMcpServer();
  });

program.parse(process.argv);
