# Writes config/runtime.yaml for the platform. Invoked by install.bat via
# '-File', with the platform root passed through the PLATFORM_ROOT
# environment variable rather than interpolated into a -Command string --
# this avoids escaping/quoting problems for paths containing spaces or
# backslashes entirely (there is nothing to unescape).
#
# Idempotent: if config\runtime.yaml already exists, it is left untouched so
# re-running install.bat never clobbers a hand-edited config.

$ErrorActionPreference = "Stop"

$root = $env:PLATFORM_ROOT
if ([string]::IsNullOrWhiteSpace($root)) {
    Write-Host "[ERROR] PLATFORM_ROOT environment variable was not set."
    exit 1
}
if (-not (Test-Path -LiteralPath $root)) {
    Write-Host "[ERROR] PLATFORM_ROOT does not exist: $root"
    exit 1
}

$configDir = Join-Path $root "config"
New-Item -ItemType Directory -Force -Path $configDir | Out-Null

$configPath = Join-Path $configDir "runtime.yaml"
if (Test-Path -LiteralPath $configPath) {
    Write-Host "[INFO] $configPath already exists -- leaving it unchanged (idempotent)."
    exit 0
}

$escapedRoot = $root.Replace('\', '\\').Replace('"', '\"')
$timestamp = (Get-Date).ToUniversalTime().ToString("o")

$content = @"
# Generated by install.bat / scripts/generate-runtime-config.ps1
# Safe to edit by hand; re-running the installer will not overwrite this file.
schemaVersion: 1
platformRoot: "$escapedRoot"
installedAt: "$timestamp"
platform: windows
"@

try {
    Set-Content -LiteralPath $configPath -Value $content -Encoding UTF8
} catch {
    Write-Host "[ERROR] Failed to write $configPath : $($_.Exception.Message)"
    exit 1
}

Write-Host "[SUCCESS] Wrote $configPath"
exit 0
