// MobSF adapter (PRD §11.4). Talks to the persistent `mobsf` compose
// service's REST API (upload -> scan -> report_json), per MobSF's official
// REST API docs (github.com/MobSF/Mobile-Security-Framework-MobSF).
//
// MobSF's REST API key is generated by MobSF itself on first startup and
// printed to its container logs (there is no way to pre-set it reliably
// across MobSF versions without inspecting the running container) --
// `security doctor` surfaces the exact command to retrieve it
// (`docker compose logs mobsf`) rather than this module guessing at it.
//
// IMPORTANT: unlike zap/nuclei, `target` here is a filesystem path to an
// APK/AAB artifact, not a URL -- mobile static analysis operates on a
// binary, not a network endpoint. Callers (the orchestrator) must route
// Android assessments to this adapter with an artifact path, matched
// against scope.allowedMobileArtifacts, not allowedDomains/allowedUrls.

import * as fs from "fs";
import * as path from "path";
import type { ToolAdapter, ToolHealth } from "./adapter";
import type { Finding } from "../findings/schema";
import type { Scope } from "../config/schema";
import { redact } from "../security/redact";

function mobsfBaseUrl(): string {
  const port = process.env.MOBSF_PORT ?? "8000";
  return `http://127.0.0.1:${port}`;
}

function mobsfApiKey(): string {
  const key = process.env.MOBSF_API_KEY;
  if (!key) {
    throw new Error(
      "MOBSF_API_KEY is not set. Retrieve it with: docker compose -f docker/docker-compose.yml logs mobsf | findstr API_KEY " +
        "(or 'grep API_KEY' on Linux/macOS), then add it to docker/.env as MOBSF_API_KEY and re-run."
    );
  }
  return key;
}

function assertMobileArtifactInScope(artifactPath: string, scope: Scope): void {
  const base = path.basename(artifactPath);
  const allowed = scope.allowedMobileArtifacts.some((pattern) => base === pattern || artifactPath.endsWith(pattern));
  if (!allowed) {
    throw new Error(
      `'${artifactPath}' is not listed in allowedMobileArtifacts in .security/scope.yaml. Add it before scanning (PRD §21: external target = denied).`
    );
  }
}

function severityFromMobsf(cvss: number | undefined, rating: string | undefined): Finding["severity"] {
  if (typeof cvss === "number") {
    if (cvss >= 9) return "critical";
    if (cvss >= 7) return "high";
    if (cvss >= 4) return "medium";
    if (cvss > 0) return "low";
  }
  const r = (rating ?? "").toLowerCase();
  if (r === "high" || r === "dangerous") return "high";
  if (r === "warning" || r === "medium") return "medium";
  if (r === "info" || r === "secure" || r === "good") return "info";
  return "info";
}

export const mobsfAdapter: ToolAdapter = {
  name: "mobsf",

  async checkHealth(): Promise<ToolHealth> {
    try {
      const res = await fetch(mobsfBaseUrl() + "/", { signal: AbortSignal.timeout(10_000) });
      if (!res.ok) {
        return { name: "mobsf", available: false, detail: `HTTP ${res.status} from ${mobsfBaseUrl()}` };
      }
      return { name: "mobsf", available: true, detail: mobsfBaseUrl() };
    } catch (err: any) {
      return {
        name: "mobsf",
        available: false,
        detail: `${err.message} -- is the 'mobsf' compose service running? (docker compose -f docker/docker-compose.yml up -d mobsf)`,
      };
    }
  },

  async run(target: string, scope: Scope): Promise<Finding[]> {
    if (!fs.existsSync(target)) {
      throw new Error(`Mobile artifact not found: ${target}`);
    }
    assertMobileArtifactInScope(target, scope);

    const apiKey = mobsfApiKey();
    const fileBuffer = fs.readFileSync(target);
    const form = new FormData();
    form.append("file", new Blob([fileBuffer]), path.basename(target));

    const uploadRes = await fetch(mobsfBaseUrl() + "/api/v1/upload", {
      method: "POST",
      headers: { Authorization: apiKey },
      body: form,
      signal: AbortSignal.timeout(120_000),
    });
    if (!uploadRes.ok) {
      throw new Error(`MobSF upload failed: HTTP ${uploadRes.status}`);
    }
    const upload = (await uploadRes.json()) as { hash: string; scan_type: string; file_name: string };

    const scanRes = await fetch(mobsfBaseUrl() + "/api/v1/scan", {
      method: "POST",
      headers: { Authorization: apiKey, "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ hash: upload.hash, scan_type: upload.scan_type }),
      signal: AbortSignal.timeout((scope.maxScanDurationMinutes ?? 15) * 60_000),
    });
    if (!scanRes.ok) {
      throw new Error(`MobSF scan failed: HTTP ${scanRes.status}`);
    }

    const reportRes = await fetch(mobsfBaseUrl() + "/api/v1/report_json", {
      method: "POST",
      headers: { Authorization: apiKey, "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ hash: upload.hash }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!reportRes.ok) {
      throw new Error(`MobSF report_json failed: HTTP ${reportRes.status}`);
    }
    const report = (await reportRes.json()) as any;

    const findings: Finding[] = [];

    // Manifest/code analysis findings (report.manifest_analysis.manifest_findings,
    // report.code_analysis.findings -- shape per MobSF's documented report_json).
    const manifestFindings: any[] = report?.manifest_analysis?.manifest_findings ?? [];
    for (const [i, f] of manifestFindings.entries()) {
      findings.push({
        id: `mobsf-manifest-${i}`,
        title: f.title ?? f.name ?? "MobSF manifest finding",
        severity: severityFromMobsf(undefined, f.severity),
        confidence: "probable",
        component: upload.file_name,
        technology: "android",
        source_location: "AndroidManifest.xml",
        description: redact(f.description ?? ""),
        evidence: [],
        reproduction: [],
        references: [],
        detected_by: ["mobsf"],
        validated_by: [],
        status: "suspected",
      });
    }

    const codeFindings: Record<string, any> = report?.code_analysis?.findings ?? {};
    let codeIndex = 0;
    for (const [ruleId, f] of Object.entries<any>(codeFindings)) {
      codeIndex += 1;
      const files = Array.isArray(f?.files) ? Object.keys(f.files) : [];
      findings.push({
        id: `mobsf-code-${ruleId}-${codeIndex}`,
        title: f?.metadata?.description ?? ruleId,
        severity: severityFromMobsf(f?.metadata?.cvss, f?.metadata?.severity),
        confidence: "probable",
        component: upload.file_name,
        technology: "android",
        source_location: files[0] ?? undefined,
        description: redact(f?.metadata?.description ?? ruleId),
        evidence: files.map((file) => redact(file)),
        reproduction: [],
        references: f?.metadata?.ref ? [String(f.metadata.ref)] : [],
        detected_by: ["mobsf"],
        validated_by: [],
        status: "suspected",
      });
    }

    return findings;
  },
};
