// OWASP ZAP adapter (PRD §11.2). Talks to the persistent `zap` compose
// service over its REST API (spider -> active scan -> alerts), per ZAP's
// official Docker API docs (zaproxy.org/docs/docker/). Requires the
// `security-platform-zap` container to be running and ZAP_API_KEY/
// ZAP_API_PORT to be set (docker/.env, generated by `security setup`).

import type { ToolAdapter, ToolHealth } from "./adapter";
import type { Finding } from "../findings/schema";
import type { Scope } from "../config/schema";
import { assertInScope } from "../security/scope-guard";
import { redact } from "../security/redact";

function zapBaseUrl(): string {
  const port = process.env.ZAP_API_PORT ?? "8090";
  return `http://127.0.0.1:${port}`;
}

function zapApiKey(): string {
  const key = process.env.ZAP_API_KEY;
  if (!key) {
    throw new Error("ZAP_API_KEY is not set. Run 'security setup' to generate docker/.env, then restart the ZAP container.");
  }
  return key;
}

async function zapGet(path: string, params: Record<string, string> = {}): Promise<any> {
  const url = new URL(zapBaseUrl() + path);
  url.searchParams.set("apikey", zapApiKey());
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
  const res = await fetch(url.toString(), { signal: AbortSignal.timeout(15_000) });
  if (!res.ok) {
    throw new Error(`ZAP API ${path} returned HTTP ${res.status}`);
  }
  return res.json();
}

function zapRiskToSeverity(risk: string | undefined): Finding["severity"] {
  switch ((risk ?? "").toLowerCase()) {
    case "high":
      return "high";
    case "medium":
      return "medium";
    case "low":
      return "low";
    default:
      return "info";
  }
}

function zapConfidenceToConfidence(confidence: string | undefined): Finding["confidence"] {
  const c = (confidence ?? "").toLowerCase();
  return c === "high" || c === "confirmed" ? "probable" : "suspected";
}

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export const zapAdapter: ToolAdapter = {
  name: "zap",

  async checkHealth(): Promise<ToolHealth> {
    try {
      const data = await zapGet("/JSON/core/view/version/");
      return { name: "zap", available: true, version: data.version };
    } catch (err: any) {
      return {
        name: "zap",
        available: false,
        detail: `${err.message} -- is the 'zap' compose service running? (docker compose -f docker/docker-compose.yml up -d zap)`,
      };
    }
  },

  async run(target: string, scope: Scope): Promise<Finding[]> {
    assertInScope(target, scope);

    await zapGet("/JSON/spider/action/scan/", { url: target });
    for (let i = 0; i < 100; i++) {
      await sleep(3000);
      const status = await zapGet("/JSON/spider/view/status/");
      if (Number(status.status) >= 100) break;
    }

    await zapGet("/JSON/ascan/action/scan/", { url: target });
    const deadline = Date.now() + (scope.maxScanDurationMinutes ?? 30) * 60_000;
    while (Date.now() < deadline) {
      await sleep(5000);
      const status = await zapGet("/JSON/ascan/view/status/");
      if (Number(status.status) >= 100) break;
    }

    const alertsResponse = await zapGet("/JSON/core/view/alerts/", { baseurl: target });
    const alerts: any[] = alertsResponse.alerts ?? [];

    return alerts.map((a, i) => ({
      id: `zap-${a.pluginId ?? "unknown"}-${i}`,
      title: a.name ?? "ZAP finding",
      severity: zapRiskToSeverity(a.risk),
      confidence: zapConfidenceToConfidence(a.confidence),
      component: target,
      technology: "web",
      endpoint: a.url ?? target,
      description: redact(a.description ?? ""),
      technical_details: a.other ? redact(a.other) : undefined,
      evidence: [a.evidence ?? ""].filter(Boolean).map(redact),
      reproduction: [] as string[],
      recommendation: a.solution ? redact(a.solution) : undefined,
      references: String(a.reference ?? "")
        .split("\n")
        .filter(Boolean),
      detected_by: ["zap"],
      validated_by: [],
      status: "suspected" as const,
    }));
  },
};
